name: Publish to WinGet
on:
  workflow_dispatch:
  release:
    types: [ released ]
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: Package.Identifier
          token: ${{ secrets.PT_WINGET }}
          installers-regex: '\.zip$'
