name: WinGet Submission on Release
# based off of https://github.com/nushell/nushell/blob/main/.github/workflows/winget-submission.yml
# based off of https://github.com/microsoft/PowerToys/blob/main/.github/workflows/package-submissions.yml
# Modified by MerrickZ https://github.com/anpho

on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  winget:
    name: Publish winget package
    runs-on: windows-latest
    steps:
      - name: Submit Notepad4 package to Windows Package Manager Community Repository
        run: |

          $wingetPackage = "zufuliu.notepad4"
          $gitToken = "${{ secrets.PT_WINGET }}"

          $github = Invoke-RestMethod -uri "https://api.github.com/repos/zufuliu/notepad4/releases" 
          # for the 1st release that is not PreRelease
          $targetRelease = $github | Where-Object -Property prerelease -match 'false' | Select-Object -First 1
          
          $installerX64Url =$targetRelease | Select -ExpandProperty assets -First 1 | Where-Object -Property name -match 'Notepad4_i18n_x64*' | Select -ExpandProperty browser_download_url
          $installerX86Url =$targetRelease | Select -ExpandProperty assets -First 1 | Where-Object -Property name -match 'Notepad4_i18n_Win32*' | Select -ExpandProperty browser_download_url
          $installerARM64Url =$targetRelease | Select -ExpandProperty assets -First 1 | Where-Object -Property name -match 'Notepad4_i18n_ARM64*' | Select -ExpandProperty browser_download_url
          $installerARMUrl =$targetRelease | Select -ExpandProperty assets -First 1 | Where-Object -Property name -match 'Notepad4_i18n_ARM__*' | Select -ExpandProperty browser_download_url
           
           # and there's more locales
          $i_ARM_en =$targetRelease | Select -ExpandProperty assets -First 1 | Where-Object -Property name -match 'Notepad4_en_ARM__*' | Select -ExpandProperty browser_download_url
          $i_arm64_en =$targetRelease | Select -ExpandProperty assets -First 1 | Where-Object -Property name -match 'Notepad4_en_ARM64_*' | Select -ExpandProperty browser_download_url
          $i_x86_en =$targetRelease | Select -ExpandProperty assets -First 1 | Where-Object -Property name -match 'Notepad4_en_Win32_*' | Select -ExpandProperty browser_download_url
          $i_x64_en =$targetRelease | Select -ExpandProperty assets -First 1 | Where-Object -Property name -match 'Notepad4_en_x64_*' | Select -ExpandProperty browser_download_url
           
          $i_arm64_it =$targetRelease | Select -ExpandProperty assets -First 1 | Where-Object -Property name -match 'Notepad4_it_ARM64_*' | Select -ExpandProperty browser_download_url
          $i_x86_it =$targetRelease | Select -ExpandProperty assets -First 1 | Where-Object -Property name -match 'Notepad4_it_Win32_*' | Select -ExpandProperty browser_download_url
          $i_x64_it =$targetRelease | Select -ExpandProperty assets -First 1 | Where-Object -Property name -match 'Notepad4_it_x64_*' | Select -ExpandProperty browser_download_url
           
          $i_arm64_ja =$targetRelease | Select -ExpandProperty assets -First 1 | Where-Object -Property name -match 'Notepad4_ja_ARM64_*' | Select -ExpandProperty browser_download_url
          $i_x86_ja =$targetRelease | Select -ExpandProperty assets -First 1 | Where-Object -Property name -match 'Notepad4_ja_Win32_*' | Select -ExpandProperty browser_download_url
          $i_x64_ja =$targetRelease | Select -ExpandProperty assets -First 1 | Where-Object -Property name -match 'Notepad4_ja_x64_*' | Select -ExpandProperty browser_download_url
           
          $i_arm64_ko =$targetRelease | Select -ExpandProperty assets -First 1 | Where-Object -Property name -match 'Notepad4_ko_ARM64_*' | Select -ExpandProperty browser_download_url
          $i_x86_ko =$targetRelease | Select -ExpandProperty assets -First 1 | Where-Object -Property name -match 'Notepad4_ko_Win32_*' | Select -ExpandProperty browser_download_url
          $i_x64_ko =$targetRelease | Select -ExpandProperty assets -First 1 | Where-Object -Property name -match 'Notepad4_ko_x64_*' | Select -ExpandProperty browser_download_url
           
          $i_arm64_sc =$targetRelease | Select -ExpandProperty assets -First 1 | Where-Object -Property name -match 'Notepad4_zh-Hans_ARM64_*' | Select -ExpandProperty browser_download_url
          $i_x86_sc =$targetRelease | Select -ExpandProperty assets -First 1 | Where-Object -Property name -match 'Notepad4_zh-Hans_Win32_*' | Select -ExpandProperty browser_download_url
          $i_x64_sc =$targetRelease | Select -ExpandProperty assets -First 1 | Where-Object -Property name -match 'Notepad4_zh-Hans_x64_*' | Select -ExpandProperty browser_download_url
           
          $i_arm64_tc =$targetRelease | Select -ExpandProperty assets -First 1 | Where-Object -Property name -match 'Notepad4_zh-Hant_ARM64_*' | Select -ExpandProperty browser_download_url
          $i_x86_tc =$targetRelease | Select -ExpandProperty assets -First 1 | Where-Object -Property name -match 'Notepad4_zh-Hant_Win32_*' | Select -ExpandProperty browser_download_url
          $i_x64_tc =$targetRelease | Select -ExpandProperty assets -First 1 | Where-Object -Property name -match 'Notepad4_zh-Hant_x64_*' | Select -ExpandProperty browser_download_url
          
          $ver = $targetRelease.tag_name -ireplace '^v'
          $publish_date = $targetRelease.published_at -ireplace "T.*"
          # getting latest wingetcreate file
          iwr https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
          .\wingetcreate update $wingetPackage -s -v $ver -u "$installerX64Url|x64" "$installerX86Url|x86" "$installerARM64Url|arm64" "$installerARMUrl|arm" "$i_ARM_en|arm|en" "$i_arm64_en|arm64|en" "$i_x86_en|x86|en" "$i_x64_en|x64|en"  "$i_arm64_it|arm64|it" "$i_x86_it|x86|it" "$i_x64_it|x64|it"  "$i_arm64_ja|arm64|ja" "$i_x86_ja|x86|ja" "$i_x64_ja|x64|ja"  "$i_arm64_ko|arm64|ko" "$i_x86_ko|x86|ko" "$i_x64_ko|x64|ko" "$i_arm64_sc|arm64|zh-Hans" "$i_x86_sc|x86|zh-Hans" "$i_x64_sc|x64|zh-Hans" "$i_arm64_tc|arm64|zh-Hant" "$i_x86_tc|x86|zh-Hant" "$i_x64_tc|x64|zh-Hant" -t $gitToken --release-notes-url $targetRelease.html_url --release-date $publish_date
